### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by joshfinnie** [nodeschool/washingtondc#1]
- [ ] Evaluate some other chapter's READMEs
- [ ] Create a README
  - [ ] Explain what NodeSchool is
  - [ ] List classes for self-paced work
  - [ ] Create a list of mentors
  - [ ] Create a list of events

**Comment by robbiethegeek** [comment]
I think we can close this for the moment.

**Comment by joshfinnie** [comment]
I agree...
