### ISSUE TITLE
We need a CoC!

### ISSUE THREAD

**Issue by joshfinnie** [nodeschool/washingtondc#10]
NodeDC has [one](https://github.com/NodeDC/CodeOfConduct) we could steal...

NodeSchool itself has [one](https://github.com/nodeschool/organizers/blob/master/code_of_conduct.md) we could steal...

Then there's the [new hotness](http://confcodeofconduct.com/) from the Ada Institute we can steal...

Thoughts?

**Comment by robbiethegeek** [comment]
Let's pilfer the NodeSchool one for the moment, and then add a milestone in the beginning of the year maybe to review / decide if we need a more in-depth / bigger umbrella CoC.

**Comment by joshfinnie** [comment]
Check out PR #11. Let's keep the comments here though.

**Comment by joshfinnie** [comment]
Closed by #11
