### ISSUE TITLE
NodeSchoolDC mentorship signup for April 16

### ISSUE THREAD

**Issue by danpaz** [nodeschool/washingtondc#23]
We're putting out our **first call for mentors** today in advance of our next nodeschool event this Saturday April 16. If you're interested in getting involved as a mentor please fill out ✨  [this google form](http://goo.gl/forms/Juul9R12G7) ✨  and then reply to this issue to let us know you did! 

(Even if you can't make it this Saturday we still want to hear from you for future events.)

And when you're done, help spread the word about the next event by sharing this link to the meetup page: http://meetu.ps/2SWs1l.

Thanks! 🙇 
- [x] @btthomas 
- [x] @Josecc 
- [x] @jdkruzr
- [x] @cralford21
- [x] @JuanCaicedo
- [x] @robbiethegeek 
- [x] @joshfinnie

**Comment by btthomas** [comment]
I filled out the form.

**Comment by Josecc** [comment]
I did as well!
