### ISSUE TITLE
Create a gitter.im channel

### ISSUE THREAD

**Issue by robbiethegeek** [nodeschool/washingtondc#3]
Added a pull request to add the badge, and you will have to allow gitter.im to write to the repo.  We are using in NYC to organize / chat and it is working great. 

gitter.im/nodeschool/washingtondc is what the badge is pointing too.

**Comment by robbiethegeek** [comment]
This is broken, the channel needs to be created on https://gitter.im/ and that will create a pull request.

**Comment by joshfinnie** [comment]
Thanks @robbiethegeek I will give it a go. Cheers!

**Comment by joshfinnie** [comment]
This was done by #4
