### ISSUE TITLE
We need a Hexdex!

### ISSUE THREAD

**Issue by joshfinnie** [nodeschool/washingtondc#5]
Some of [these](http://nodeschool.io/hexdex.html) are pretty awesome. I think DC could have an awesome one too.

Unfortunately, I am a terrible designer. Anyone here have any ideas?

**Comment by robbiethegeek** [comment]
YES!  I have been talking this for a while!! :) :+1:

**Comment by diptajbasu** [comment]
Hi guys, I’ve had an awesome time at the NodeSchool sessions :smile:

I attached a logo concept that includes some DC-style rowhouses, monuments and some “node blossoms.” Please let me know what you think when you get the chance!

![dc_hexdex](https://cloud.githubusercontent.com/assets/7990216/9895488/2b1c1cc4-5bfe-11e5-92b2-e135f3b917b6.png)

**Comment by robbiethegeek** [comment]
I love it!!  Only thing I think needs changing is the color for the words NodeSchool DC it isn't easy to read maybe black or solid blue?

**Comment by joshfinnie** [comment]
Or yellow to mix it up a little bit (back seat designing)

@diptajbasu this is great! Thanks for taking the time to do this!

**Comment by diptajbasu** [comment]
Great ideas guys! I was thinking a red/white/blue color palette to reflect being in the nation’s capital, but somehow ended up making the blossoms pinkish (though they could just as easily be more red).

What should brand colors be for the NodeSchool DC website? That potentially could impact color choices for the hexdex logo? Red/white/blue might work, with yellow as an accent color, as Josh was thinking?

I’ve attached updated images with different font colors, as requested. Let me know your thoughts when you have time.

![dc_hexdex_black](https://cloud.githubusercontent.com/assets/7990216/9923389/6ba9df0a-5cc2-11e5-8814-455fcef0aabc.png)
![dc_hexdex_blue](https://cloud.githubusercontent.com/assets/7990216/9923392/7d46f982-5cc2-11e5-8db8-3e1d3f8fd563.png)
![dc_hexdex_yellow](https://cloud.githubusercontent.com/assets/7990216/9923393/83f93a4c-5cc2-11e5-87c8-ae90dfca1eb5.png)

**Comment by robbiethegeek** [comment]
I think the blue is my favorite and still readable!  @diptajbasu you rock!

**Comment by danpaz** [comment]
+1 to the blue this looks great!

**Comment by robbiethegeek** [comment]
Anyone else have any feedback? Would love to add this to nodeschool.io and to start a chat about creating stickers! :)

**Comment by joshfinnie** [comment]
+1 for the blue lettering. This is awesome!

**Comment by diptajbasu** [comment]
Hey guys, I added a PNG and SVG (and the source Adobe Illustrator file) of the hexdex with the blue lettering here: https://github.com/diptajbasu/nodeschool-dc-hexdex-logo

**Comment by robbiethegeek** [comment]
Hey @diptajbasu I added it to the nodeschool.io site.  Thanks can you submit a pull request here with the files maybe in a folder called hexdex ?  PS added you to the commit and the pr as the creator so thanks and wanted to make sure you were publically acknowledged in the end.  Is there any chance you can make a square version that has all the detail so I can use it on the twitter profile without cropping and we can use in in other places that a hexdex isn't optimal... :)

**Comment by diptajbasu** [comment]
Thanks @robbiethegeek ! I submitted a PR with the hexdex files. Adding a square PNG here as a preview, let me know what you think (happy to adjust) and I'll submit the square artwork files once approved.

![dc_square_blue](https://cloud.githubusercontent.com/assets/7990216/10036587/8c1d99fc-6177-11e5-8839-8d77440207e8.png)

**Comment by joshfinnie** [comment]
Closed with #8

**Comment by robbiethegeek** [comment]
This is amazing... I love the hexdex but haven't found a reasonable place to make them into stickers where as the squares...no problem :) already updated the twitter account to use the square version.  This is great thanks again!!

**Comment by joshfinnie** [comment]
@robbiethegeek I am going to open another issue about the printing of stickers... TrackMaven uses [StickerMule](https://www.stickermule.com) to much success...
