### ISSUE TITLE
We need a website!

### ISSUE THREAD

**Issue by joshfinnie** [nodeschool/washingtondc#7]
I think a `gh-pages` website should do... thoughts?

**Comment by robbiethegeek** [comment]
Yes sir I concur, we should look around and get a simple one that we can
steal from another chapter in place then iterate :)

**Comment by joshfinnie** [comment]
It's a start... http://nodeschool.io/washingtondc/

Make PRs to the `gh-pages` branch...

**Comment by joshfinnie** [comment]
Wow, this is going so much better than I ever imagined! I am going to close out this issue as it's pretty great as is and we can make PRs for improvements!
