### ISSUE TITLE
We need stickers!

### ISSUE THREAD

**Issue by joshfinnie** [nodeschool/washingtondc#9]
Now that [our amazing hex](https://github.com/nodeschool/washingtondc/blob/23b813aa95ef0826bdcb9b93bdd9c25cc9323f58/hexdex/dc_hexdex_blue.png) is completed, we need to figure out how and where to get some of theme made into stickers!

**Comment by joshfinnie** [comment]
At TrackMaven, we use StickerMule for our stickers. [Die cut ones](https://www.stickermule.com/products/die-cut-stickers) will run us about $136 for 500.

**Comment by robbiethegeek** [comment]
Done and done...
